package com.upgrade.gui.pages;

import java.lang.invoke.MethodHandles;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.ui.Select;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.qaprosoft.carina.core.foundation.utils.Configuration;
import com.qaprosoft.carina.core.foundation.utils.R;
import com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement;
import com.qaprosoft.carina.core.gui.AbstractPage;

public class NonDMFunnelPage extends AbstractPage {
    private static final Logger LOGGER = LoggerFactory.getLogger(MethodHandles.lookup().lookupClass());

    @FindBy(id = "aria-autogenerated-id3")
    private ExtendedWebElement loanAmount;
    
    @FindBy(name = "loan-purpose")
    private ExtendedWebElement loanPurpose;
    
    @FindBy(xpath = "//*[@id=\"root\"]/div/main/div/div/div/div[2]/div[2]/div[2]/form/div/div/div[3]/button")
    private ExtendedWebElement clickCheckYourRate;
    
    public NonDMFunnelPage(WebDriver driver) {
        super(driver);
        setPageAbsoluteURL(R.CONFIG.get(Configuration.Parameter.URL.getKey()));
    }

    public void enterLoanAmt(String selectedLoanAmt) {
        loanAmount.getElement().sendKeys(selectedLoanAmt);
    }
    
    public void selectLoanPurpose(String selectedLoanPurpose) {
    	Select loanPurposeDropDown = new Select(loanPurpose.getElement());
        loanPurposeDropDown.selectByValue(selectedLoanPurpose);
    }
     
    public void checkYourRate() {
    	clickCheckYourRate.click();
    }
    
}
